include:
  - project: 'codelutin/ci'
    file: '/ci.yml'

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS:   "6200805"
  MAVEN_REPO_PATH: "/var/local/shared-m2-repository"
  MAVEN_OPTS: "-Dmaven.repo.local=${MAVEN_REPO_PATH}"

stages:
- build
- package
- deploy
- check-releasable
- sonar

#build:dependency-tree:
#  image: maven:3.6-openjdk-15
#  stage: build
#  rules:
#    - if: '$CI_PIPELINE_SOURCE != "schedule"'
#      when: manual
#  script:
#    - mvn dependency:tree
#  tags:
#    - sticky

build:compile-only:
  image: maven:3.6-openjdk-15
  stage: build
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
      - fishola-admin/target/dist-demo
      - fishola-admin/target/dist-beta
  script:
    - mvn clean package -Dmaven.test.skip
  rules:
    - if: $CI_COMMIT_BRANCH != "develop"
      when: manual
  tags:
    - sticky
    - docker

build:compile-with-tests:
  image: maven:3.6-openjdk-15
  stage: build
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
      - fishola-admin/target/dist-demo
      - fishola-admin/target/dist-beta
  script:
    - ls -al /var/local/
    - du --si --max-depth=1 /var/local/
    - mvn clean package
    - ls -al /var/local/
    - du --si --max-depth=1 /var/local/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE != "schedule"'
      when: always
  tags:
    - sticky
    - docker

# must be run after the build stage
package:android-demo:
  image: openjdk:9-jdk
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  cache:
    paths:
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - wget --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
    - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
    - chmod +x fishola-mobile/android/gradlew
    # temporarily disable checking for EPIPE error and use yes to accept all licenses
    - set +o pipefail
    - yes | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
    - set -o pipefail
    - cd fishola-mobile
    - mv target/dist-demo target/dist
    - ./node/node node/node_modules/npm/bin/npx-cli.js cap copy
    - cd android
    - cat ${KEYSTORE_FISHOLA_JKS} | base64 -d > keystore-fishola.jks
    - cat ${SIGNING_CONFIG} > app/signin.properties
    - ./gradlew clean
    - ./gradlew assembleDemo
    - cp app/build/outputs/apk/demo/release/*.apk ../../
  artifacts:
    name: "fishola-android-demo-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./*.apk
    expire_in: 2 weeks
  tags:
    - sticky

# must be run after the build stage
package:android-beta:
  image: openjdk:9-jdk
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  cache:
    paths:
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - wget --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
    - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
    - chmod +x fishola-mobile/android/gradlew
    # temporarily disable checking for EPIPE error and use yes to accept all licenses
    - set +o pipefail
    - yes | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
    - set -o pipefail
    - cd fishola-mobile
    - mv target/dist-beta target/dist
    - ./node/node node/node_modules/npm/bin/npx-cli.js cap copy
    - cd android
    - cat ${KEYSTORE_FISHOLA_JKS} | base64 -d > keystore-fishola.jks
    - cat ${SIGNING_CONFIG} > app/signin.properties
    - ./gradlew clean
    - ./gradlew assembleBeta
    - cp app/build/outputs/apk/beta/release/*.apk ../../
  artifacts:
    name: "fishola-android-beta-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./*.apk
    expire_in: 2 weeks
  tags:
    - sticky

# must be run after the build stage
package:android-production:
  image: openjdk:9-jdk
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  cache:
    paths:
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - wget --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
    - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
    - chmod +x fishola-mobile/android/gradlew
    # temporarily disable checking for EPIPE error and use yes to accept all licenses
    - set +o pipefail
    - yes | android-sdk-linux/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
    - set -o pipefail
    - cd fishola-mobile
    - mv target/dist-production target/dist
    - ./node/node node/node_modules/npm/bin/npx-cli.js cap copy
    - cd android
    - cat ${KEYSTORE_FISHOLA_JKS} | base64 -d > keystore-fishola.jks
    - cat ${SIGNING_CONFIG} > app/signin.properties
    - ./gradlew clean
    - ./gradlew assembleProduction
    - cp app/build/outputs/apk/production/release/*.apk ../../
  artifacts:
    name: "fishola-android-beta-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./*.apk
    expire_in: 2 weeks
  tags:
    - sticky

package:docker-demo:
  image: registry.nuiton.org/codelutin/dockerfiles:docker
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: always
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
      - fishola-mobile/target/dist-demo
      - fishola-admin/target/dist-demo
  script:
    - ls -al fishola-backend/target
    - ls -al fishola-mobile/target
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.nuiton.org
    - docker build --no-cache --file fishola-backend/src/main/docker/Dockerfile.demo -t registry.nuiton.org/inrae/fishola:backend-demo fishola-backend
    - docker build --no-cache --file fishola-mobile/docker/Dockerfile.demo -t registry.nuiton.org/inrae/fishola:mobile-demo fishola-mobile
    - docker build --no-cache --file fishola-admin/docker/Dockerfile.demo -t registry.nuiton.org/inrae/fishola:admin-demo fishola-admin
    - docker push registry.nuiton.org/inrae/fishola
    - docker logout registry.nuiton.org
    - /usr/bin/curl https://webhooks.demo.codelutin.com/redeploy-fishola-demo
  tags:
    - sticky
    - docker

package:docker-beta:
  image: registry.nuiton.org/codelutin/dockerfiles:docker
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
      - fishola-mobile/target/dist-beta
      - fishola-admin/target/dist-beta
  script:
    - ls -al fishola-backend/target
    - ls -al fishola-mobile/target
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.nuiton.org
    - docker build --no-cache --file fishola-backend/src/main/docker/Dockerfile.beta -t registry.nuiton.org/inrae/fishola:backend-beta fishola-backend
    - docker build --no-cache --file fishola-mobile/docker/Dockerfile.beta -t registry.nuiton.org/inrae/fishola:mobile-beta fishola-mobile
    - docker build --no-cache --file fishola-admin/docker/Dockerfile.beta -t registry.nuiton.org/inrae/fishola:admin-beta fishola-admin
    - docker push registry.nuiton.org/inrae/fishola
    - docker logout registry.nuiton.org
  tags:
    - sticky
    - docker

package:backend:
  image: debian:latest
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
  script:
    - apt update && apt install -y zip && apt clean
    - mkdir -p fishola-backend-$CI_COMMIT_SHORT_SHA/config
    - cp -r fishola-backend/target/lib fishola-backend/target/fishola-backend-*-runner.jar  fishola-backend-$CI_COMMIT_SHORT_SHA/
    - cp doc/application.properties.sample fishola-backend-$CI_COMMIT_SHORT_SHA/config/application.properties
  artifacts:
    name: "fishola-backend-$CI_COMMIT_SHORT_SHA"
    paths:
      - fishola-backend-$CI_COMMIT_SHORT_SHA
    expire_in: 2 weeks
  tags:
    - sticky

deploy:demo:
  image: debian:latest
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  script:
    - apt update && apt install -y curl && apt clean
    - /usr/bin/curl https://webhooks.demo.codelutin.com/redeploy-fishola-demo

deploy:beta:
  image: debian:latest
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
  script:
    - apt update && apt install -y curl && apt clean
    - /usr/bin/curl https://webhooks.demo.codelutin.com/redeploy-fishola-beta

sonarqube:
  image: maven:3.6-openjdk-15
  stage: sonar
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
  cache:
    paths:
      - fishola-backend/target/lib
      - fishola-backend/target/fishola-backend-*-runner.jar
      - fishola-mobile/node
      - fishola-mobile/node_modules
      - fishola-mobile/target/dist-demo
      - fishola-mobile/target/dist-beta
      - fishola-mobile/target/dist-production
      - fishola-admin/target/dist-demo
      - fishola-admin/target/dist-beta
  script:
    - mvn -e -U clean verify -DskipRelease org.sonarsource.scanner.maven:sonar-maven-plugin:$MAVEN_SONAR_PLUGIN_VERSION:sonar -Dsonar.host.url="$SONAR_INSTANCE_URL" -Dsonar.projectKey=fr.inrae:fishola -Dsonar.exclusions='**/js/libs/*','**/target/*','**/generated*/*'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - sticky
    - docker

#build:ios:
#  stage: build
#  when: manual
#  script:
#    - cd fishola-mobile/ios/App
#    - xcodebuild clean -project App.xcodeproj -scheme App | xcpretty
#    - pod install
#    - xcodebuild -workspace App.xcworkspace -scheme App clean archive -configuration release -sdk iphoneos -archivePath App.xcarchive
#    - xcodebuild -exportArchive -archivePath App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath Fishola.ipa
#
#  tags:
#    - ios

#check-releasable:
#  image: registry.nuiton.org/codelutin/dockerfiles:maven-release-debian9-openjdk8-with-frequent-libraries
#  stage: check-releasable
#  script:
#    - mvn clean verify -e -U -DperformRelease -Dredmine.skipGenerateChanges -Dmaven.javadoc.skip
#    - rm * .git* -rf || true
#  only:
#    - /^develop.*$/
#  when: manual
#  tags:
#    - tmpfs
#
#daily-check-releasable:
#  image: registry.nuiton.org/codelutin/dockerfiles:maven-release-debian9-openjdk8-with-frequent-libraries
#  stage: check-releasable
#  script:
#    - mvn clean verify -e -U -DperformRelease -Dredmine.skipGenerateChanges -Dmaven.javadoc.skip
#    - rm * .git* -rf || true
#  only:
#    - schedules
#  tags:
#    - tmpfs
