###
# #%L
# Fishola :: Backend
# %%
# Copyright (C) 2019 - 2020 INRAE - UMR CARRTEL
# %%
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #L%
###
# Configuration file
# key = value

fishola.version=%(project.version)
fishola.git-revision=%(git.commit.id.describe)
fishola.build-date=%(maven.build.timestamp)

quarkus.http.cors=true
#quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081
#quarkus.http.cors.methods=GET,PUT,POST,OPTIONS
##quarkus.http.cors.headers=Content-Type,Cookie
#quarkus.http.cors.exposed-headers=Content-Type,Cookie
#quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081

# La synchro des images ne fonctionne pas en HTTP/2 donc on le désactive pour l'instant
quarkus.http.http2=false

%prod.quarkus.log.console.enable=false
%prod.quarkus.log.file.enable=true
quarkus.log.file.path=fishola-backend.log
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.max-backup-index=10

quarkus.http.access-log.enabled=true

#quarkus.log.level=DEBUG
quarkus.log.category."fr.inrae".level=DEBUG

# Ces propriétés sont à définir dans le fichier `fishola-backend/.env`
#%dev.quarkus.datasource.url=jdbc:postgresql://docker_pg/fishola
#%dev.quarkus.datasource.username=postgres
#%dev.quarkus.datasource.password=whatever

%demo.quarkus.datasource.jdbc.url=jdbc:postgresql://docker_pg/fishola
%demo.quarkus.datasource.username=postgres
%demo.quarkus.datasource.password=whatever

#quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=3
quarkus.datasource.jdbc.max-size=20

%dev.fishola.jwt-secret=v3ry 53cr37 k3y
%demo.fishola.jwt-secret=v3ry 53cr37 k3y

%demo.fishola.backend-base-url=https://fishola.demo.codelutin.com

%dev.fishola.smtp-starttls=false
%dev.fishola.smtp-host=docker_mail
%dev.fishola.smtp-port=25

%demo.fishola.smtp-starttls=true
%demo.fishola.smtp-host=mail.codelutin.com
%demo.fishola.smtp-port=2525

%dev.fishola.async-emails=false
fishola.async-emails-every=30s

fishola.feedback-mail-to=fishola-lutins@list.forge.codelutin.com

# Ne fonctionne pas pour l'instant mais ça devrait venir avec les prochaines versions : https://github.com/quarkusio/quarkus/issues/9671
quarkus.resteasy.gzip.enabled=true

