# Configuration file
# key = value

quarkus.http.cors=true
#quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081
#quarkus.http.cors.methods=GET,PUT,POST,OPTIONS
##quarkus.http.cors.headers=Content-Type,Cookie
#quarkus.http.cors.exposed-headers=Content-Type,Cookie
#quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081

#quarkus.log.level=DEBUG
quarkus.log.category."fr.inra".level=DEBUG

quarkus.datasource.url=jdbc:postgresql://docker_pg/fishola
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=postgres
quarkus.datasource.min-size=3
quarkus.datasource.max-size=10
