###
# #%L
# Fishola :: Backend
# %%
# Copyright (C) 2019 - 2021 INRAE - UMR CARRTEL
# %%
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #L%
###
# Configuration file
# key = value

fishola.version=%(project.version)
fishola.git-revision=%(git.commit.id.describe)
fishola.build-date=%(maven.build.timestamp)

quarkus.http.cors.enabled=true
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083
quarkus.http.cors.methods=GET,PUT,POST,OPTIONS,DELETE
quarkus.http.cors.headers=Content-Type,Cookie
quarkus.http.cors.exposed-headers=Content-Type,Cookie
#quarkus.http.cors.origins=http://localhost:8080,http://localhost:8081

# La synchro des images ne fonctionne pas en HTTP/2 donc on le désactive pour l'instant
quarkus.http.http2=false

# Les requêtes de synchro des images peuvent être lourdes, on augmente la valeur par défaut (10M)
quarkus.http.limits.max-body-size=20M
%prod.quarkus.log.console.enable=false
%prod.quarkus.log.file.enable=true
quarkus.log.file.path=fishola-backend.log
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.max-backup-index=10

quarkus.http.access-log.enabled=true

#quarkus.log.level=DEBUG
quarkus.log.category."fr.inrae".level=DEBUG

# Ces propriétés sont à définir dans le fichier `fishola-backend/.env`
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://docker_pg/fishola
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=whatever

%demo.quarkus.datasource.jdbc.url=jdbc:postgresql://docker_pg/fishola
%demo.quarkus.datasource.username=postgres
%demo.quarkus.datasource.password=whatever

#quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=3
quarkus.datasource.jdbc.max-size=20

%dev.fishola.jwt-secret=v3ry 53cr37 k3y
%demo.fishola.jwt-secret=v3ry 53cr37 k3y

%demo.fishola.backend-base-url=https://fishola.demo.codelutin.com

## Configuration de Quarkus Mailer
%dev.quarkus.mailer.start-tls=DISABLED
%dev.quarkus.mailer.host=localhost
%dev.quarkus.mailer.port=41025
%dev.quarkus.mailer.from=fishola@codelutin.com
%dev.quarkus.mailer.mock=false

%demo.quarkus.mailer.start-tls=REQUIRED
%demo.quarkus.mailer.ssl=true
%demo.quarkus.mailer.host=mail.codelutin.com
%demo.quarkus.mailer.port=2525

%dev.fishola.async-emails=false
%dev.fishola.backend-base-url=https://localhost:8080
fishola.feedback-mail-to=fishola-lutins@list.forge.codelutin.com
fishola.global-dashboard-cache-size=500

# Ne fonctionne pas pour l'instant mais ça devrait venir avec les prochaines versions : https://github.com/quarkusio/quarkus/issues/9671
quarkus.resteasy.gzip.enabled=true

# Depuis Quarkus 1.13, les dates sont formattées en ISO-8601. Pour rester rétro-compatible on continue de sérialiser en timestamp
quarkus.jackson.write-dates-as-timestamps=true
%dev.fishola.admin-password=azerty

