--
-- #%L
-- Fishola :: Backend
-- %%
-- Copyright (C) 2019 - 2026 INRAE - UMR CARRTEL
-- %%
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
-- #L%
--

-- Nouvelle catégorie de badge "concours" (#90), préparant V2.5.0. Postgres interdit
-- d'utiliser une valeur d'enum fraîchement ajoutée dans la même transaction que son ajout
-- ("unsafe use of new value ... New enum values must be committed before they can be
-- used.") -- Flyway exécutant chaque script dans sa propre transaction, cet ALTER TYPE
-- doit être isolé dans son propre fichier de migration, committé avant que V2.5.0 ne
-- l'utilise dans un INSERT.
ALTER TYPE public.gamification_badge_category ADD VALUE 'concours';
