# Generated by Django 5.2.16 on 2026-07-18 10:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Entrée de journal',
                'verbose_name_plural': "Journal d'activité",
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('catch_time', models.TimeField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('kept', models.BooleanField()),
                ('quantity', models.IntegerField(default=1)),
                ('size_class', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capture',
                'verbose_name_plural': 'Captures',
                'db_table': 'catch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('insee_com', models.CharField(max_length=5, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_hash', models.TextField(unique=True)),
                ('collection_method', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.TextField()),
                ('total', models.IntegerField(default=0)),
                ('inserted', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
                'db_table': 'import_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('line', models.IntegerField()),
                ('column_name', models.TextField(blank=True, null=True)),
                ('stage', models.TextField()),
                ('code', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Erreur d'import",
                'verbose_name_plural': "Erreurs d'import",
                'db_table': 'import_row_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('export_as', models.TextField()),
                ('built_in', models.BooleanField(default=False)),
                ('mandatory_size', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('export_as', models.TextField()),
                ('built_in', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'db_table': 'technique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('mode', models.CharField(max_length=32)),
                ('name', models.TextField()),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('hidden', models.BooleanField(default=False)),
                ('collection_method', models.CharField(default='saisie_pecheur', max_length=32)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('export_as', models.TextField()),
                ('water_entity_code', models.CharField(blank=True, max_length=10, null=True)),
                ('kind', models.CharField(default='STILL', max_length=16)),
                ('nature', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entité hydrographique',
                'verbose_name_plural': 'Entités hydrographiques',
                'db_table': 'water_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesSizeBounds',
            fields=[
                ('species', models.OneToOneField(db_column='species_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.species')),
                ('min_size_cm', models.IntegerField(blank=True, null=True)),
                ('max_size_cm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bornes de taille par espèce',
                'verbose_name_plural': 'Bornes de taille par espèce',
                'db_table': 'species_size_bounds',
                'managed': False,
            },
        ),
    ]
